import { Container } from "../components/Container";
import Head from "next/head";
import { Navbar } from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Container>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus eius
            perferendis recusandae dicta alias ut. Libero esse inventore
            provident delectus amet pariatur laborum neque, placeat, quam sit
            magni eos quae!
          </p>
        </Container>
      </header>
    </>
  );
}
